#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}

# =============================================================================

COMMIT_MSG_FILE="$1"

SUBJECT=$(grep -Ee "^[^#]" "$COMMIT_MSG_FILE" | head -n 1)
BODY=$(grep -Ee "^$|^[^#]" "$COMMIT_MSG_FILE" | tail -n +2)
EMPTYLINE=$(head -n 1 <<< "$BODY")

echo "${#SUBJECT}"
echo "${#BODY}"
echo "${#EMPTYLINE}"

# The first non-comment non-empty line is the subject line, at most 50 chars.
if [[ ${#SUBJECT} -gt 50 ]]; then
	printf "Error: Subject is longer than 50 chars (counted %d chars)" ${#SUBJECT}
	exit 1
fi

# The second line must be empty.
if [[ ${#EMPTYLINE} -gt 0 ]]; then
	printf "Error: An empty line should separate the subject from the body"
	exit 1
fi

# Every line in the body must be at most 72 chars.
while read -r line
do
	if [[ ${#line} -gt 72 ]]; then
		printf "Error: Body is longer than 72 chars (counted %d chars)" ${#line}
		exit 1
	fi
done <<< "$BODY"
