#!/bin/bash
# Add a list of files in the format
# - file1:
# - file2:
# to the body of the commit message, just after '#FILES'.
# Does nothing if the '#FILES' doesn't exist.

COMMIT_EDITMSG="$1"
COMMIT_SOURCE="$2"
SHA1="$3"

if [[ $COMMIT_SOURCE = template ]]; then
	TMPFILE=$(mktemp "${TMPDIR:-/tmp}/git-add-status-list.XXXXXXXXXX")
	git diff --cached --name-only | sed -E -e 's/(.*)/#- \1:/g' >"$TMPFILE"
	sed -i -e "/# FILES/r $TMPFILE" "$COMMIT_EDITMSG"
	rm "$TMPFILE"
fi
